# Generated by Django 5.2.4 on 2025-12-24 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0005_change_quantity_to_integer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique location code e.g. WH-MAIN, SHOP-01', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Location name e.g. Main Warehouse, Retail Shop', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional location details', null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether location is active for transactions')),
                ('allow_sales', models.BooleanField(default=True, help_text='Whether POS sales are allowed from this location')),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='Allow stock to go negative (backorders)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Location',
                'verbose_name_plural': 'Inventory Locations',
                'db_table': 'inventory_locations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit - unique product identifier', max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, help_text='Barcode/UPC for scanning', max_length=100, null=True, unique=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Average cost per unit (for COGS calculation)', max_digits=10)),
                ('default_selling_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Default retail price', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g., 18.00 for 18% VAT)', max_digits=5)),
                ('tax_inclusive', models.BooleanField(default=False, help_text='Whether default price includes tax')),
                ('reorder_level', models.IntegerField(default=0, help_text='Stock level that triggers reorder alert')),
                ('reorder_quantity', models.IntegerField(default=0, help_text='Suggested quantity to reorder')),
                ('track_inventory', models.BooleanField(default=True, help_text='Whether to track stock levels for this item')),
                ('allow_backorder', models.BooleanField(default=False, help_text='Allow sales when out of stock')),
                ('is_active', models.BooleanField(default=True, help_text='Whether item can be sold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_items', to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.OneToOneField(help_text='Link to finished product catalog', on_delete=django.db.models.deletion.PROTECT, related_name='stock_item', to='sales.finishedproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stock_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'db_table': 'inventory_stock_items',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField(default=0, help_text='Physical quantity available')),
                ('quantity_reserved', models.IntegerField(default=0, help_text='Quantity allocated but not yet shipped (for future orders)')),
                ('last_counted_at', models.DateTimeField(blank=True, help_text='Last physical stock count date', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.inventorylocation')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'Stock Level',
                'verbose_name_plural': 'Stock Levels',
                'db_table': 'inventory_stock_levels',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase Receipt'), ('sale', 'Sale'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Location Transfer'), ('return', 'Customer Return'), ('damage', 'Damaged/Wastage'), ('recount', 'Stock Recount')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantity changed (positive for increase, negative for decrease)')),
                ('quantity_before', models.IntegerField(help_text='Stock level before this movement')),
                ('quantity_after', models.IntegerField(help_text='Stock level after this movement')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for this movement', max_digits=10, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, help_text='Total value of movement (quantity * unit_cost)', max_digits=20, null=True)),
                ('reference_type', models.CharField(blank=True, help_text='Type of source document (e.g., pos_transaction, purchase_order)', max_length=50, null=True)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of source document', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this movement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventorylocation')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'inventory_stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorylocation',
            index=models.Index(fields=['is_active', 'allow_sales'], name='idx_location_active_sales'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['is_active', 'track_inventory'], name='idx_stock_item_active'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['barcode'], name='idx_stock_item_barcode'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['stock_item', 'location'], name='idx_stock_level_item_loc'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['quantity_on_hand'], name='idx_stock_level_qty'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together={('stock_item', 'location')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', 'created_at'], name='idx_movement_item_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['location', 'created_at'], name='idx_movement_loc_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='idx_movement_type'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='idx_movement_reference'),
        ),
    ]
