# Generated by Django 5.2.4 on 2025-12-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='sales_count',
            field=models.IntegerField(default=0, help_text='Total number of times this item has been sold (for popularity ranking)'),
        ),
    ]
