# Generated by Django 5.2.4 on 2025-12-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockitem_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='button_color',
            field=models.CharField(blank=True, help_text='Hex color code for Quick Service button (e.g., #3B82F6)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='default_quantity',
            field=models.IntegerField(blank=True, default=1, help_text='Default quantity when added via Quick Service', null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, help_text='Order for UI display in Quick Service panel (lower = higher priority)', null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='icon_name',
            field=models.CharField(blank=True, help_text="Icon identifier for Quick Service button (e.g., 'printer', 'copy')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='is_quick_access',
            field=models.BooleanField(default=False, help_text='Whether to show in POS Quick Service panel'),
        ),
    ]
