# Generated by Django 5.2.4 on 2025-12-26 02:34

from django.db import migrations


def migrate_quick_service_items_to_stock_items(apps, schema_editor):
    """
    Migrate data from POSQuickServiceItem to StockItem.
    Copy display settings from quick service items to their corresponding stock items.
    """
    try:
        POSQuickServiceItem = apps.get_model('pos', 'POSQuickServiceItem')
    except LookupError:
        # POSQuickServiceItem was removed in later POS migrations. On fresh installs where
        # POS migrations run first, this data migration must be a no-op.
        print("POSQuickServiceItem model not found, skipping quick service migration")
        return

    StockItem = apps.get_model('inventory', 'StockItem')

    migrated_count = 0

    for quick_item in POSQuickServiceItem.objects.all():
        stock_item = quick_item.stock_item

        # Update stock item with quick service settings
        stock_item.is_quick_access = True
        stock_item.display_order = quick_item.display_order
        stock_item.button_color = quick_item.button_color
        stock_item.icon_name = quick_item.icon_name
        stock_item.default_quantity = quick_item.default_quantity

        stock_item.save()
        migrated_count += 1

    print(f"✅ Migrated {migrated_count} quick service items to stock items")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - clear quick access flags from stock items.
    """
    # If StockItem no longer exists (e.g., inventory overhaul), nothing to reverse.
    try:
        StockItem = apps.get_model('inventory', 'StockItem')
    except LookupError:
        return

    StockItem.objects.filter(is_quick_access=True).update(
        is_quick_access=False,
        display_order=None,
        button_color=None,
        icon_name=None,
        default_quantity=None
    )

    print("✅ Reversed quick service migration")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockitem_button_color_stockitem_default_quantity_and_more'),
        ('pos', '0001_initial'),  # Add POS dependency to access POSQuickServiceItem
    ]

    operations = [
        migrations.RunPython(
            migrate_quick_service_items_to_stock_items,
            reverse_code=reverse_migration
        ),
    ]
