# Generated by Django 5.2.4 on 2026-01-04 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, help_text='Purchase order number (e.g., PO-2026-001)', max_length=255, unique=True)),
                ('order_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Supplier'), ('confirmed', 'Confirmed'), ('partially_received', 'Partially Received'), ('received', 'Fully Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all line items', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal + tax - discount', max_digits=12)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('supplier_notes', models.TextField(blank=True, help_text='Notes sent to supplier', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-order_date', '-po_number'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(db_index=True, help_text='GRN number (e.g., GRN-2026-001)', max_length=255, unique=True)),
                ('received_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('inspected', 'Quality Inspected'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('quality_passed', models.BooleanField(default=True, help_text='Did the goods pass quality inspection?')),
                ('delivery_note_number', models.CharField(blank=True, help_text="Supplier's delivery note number", max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspected_grns', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_grns', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='suppliers.supplier')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'Goods Received Note',
                'verbose_name_plural': 'Goods Received Notes',
                'ordering': ['-received_date', '-grn_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(help_text='Line number in the order')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity ordered', max_digits=10)),
                ('unit_of_measure', models.CharField(default='units', help_text='e.g., units, kg, meters', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage (e.g., 18.00 for 18%)', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Quantity × Unit Price', max_digits=12)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, help_text='Quantity received so far', max_digits=10)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, help_text='Quantity received in this GRN', max_digits=10)),
                ('quantity_accepted', models.DecimalField(decimal_places=2, default=0, help_text='Quantity accepted after inspection', max_digits=10)),
                ('quantity_rejected', models.DecimalField(decimal_places=2, default=0, help_text='Quantity rejected (damaged, incorrect, etc.)', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Inspection notes, damage reports, etc.', null=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.goodsreceivednote')),
                ('purchase_order_item', models.ForeignKey(help_text='Link to original PO item', on_delete=django.db.models.deletion.PROTECT, related_name='grn_items', to='purchases.purchaseorderitem')),
            ],
            options={
                'verbose_name': 'GRN Item',
                'verbose_name_plural': 'GRN Items',
                'ordering': ['purchase_order_item__line_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Type of event (e.g., created, sent, confirmed)', max_length=50)),
                ('message', models.TextField(help_text='Event description')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Timeline',
                'verbose_name_plural': 'Purchase Order Timeline Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='purchases_p_po_numb_ba9e90_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'order_date'], name='purchases_p_supplie_299bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'order_date'], name='purchases_p_status_666568_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['grn_number'], name='purchases_g_grn_num_d7e1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['purchase_order', 'received_date'], name='purchases_g_purchas_77cb19_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['status'], name='purchases_g_status_5d05b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together={('purchase_order', 'line_number')},
        ),
    ]
