# Generated by Django 5.2.4 on 2026-01-04 09:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(db_index=True, help_text="Supplier's invoice/bill number", max_length=255)),
                ('internal_reference', models.CharField(db_index=True, help_text='Our internal reference number', max_length=255, unique=True)),
                ('bill_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(db_index=True)),
                ('payment_date', models.DateField(blank=True, help_text='Date when fully paid', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sum of all line items', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='Subtotal + tax - discount', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid so far', max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, help_text='Remaining balance to pay', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_supplier_bills', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_supplier_bills', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Link to purchase order (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='purchases.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Bill',
                'verbose_name_plural': 'Supplier Bills',
                'ordering': ['-bill_date', '-internal_reference'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference, cheque number, etc.', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_cleared', models.BooleanField(default=False)),
                ('cheque_cleared_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bill_payments', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchases.supplierbill')),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supplierbill',
            index=models.Index(fields=['bill_number', 'supplier'], name='purchases_s_bill_nu_6e4f43_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierbill',
            index=models.Index(fields=['internal_reference'], name='purchases_s_interna_b64cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierbill',
            index=models.Index(fields=['status', 'due_date'], name='purchases_s_status_681cc7_idx'),
        ),
    ]
