# Generated by Django 5.2.4 on 2026-01-05 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_suppliercreditnote'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Scanned bill file (PDF/JPG/PNG)', upload_to='bill-scans/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type: application/pdf, image/jpeg, image/png', max_length=50)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('textract_response', models.JSONField(blank=True, help_text='Raw Textract OCR response', null=True)),
                ('claude_response', models.JSONField(blank=True, help_text='Raw Claude extraction response', null=True)),
                ('extracted_data', models.JSONField(blank=True, help_text='Structured extracted data with confidence scores', null=True)),
                ('supplier_match_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score for supplier match (0.00-1.00)', max_digits=5, null=True)),
                ('user_edited_fields', models.JSONField(default=dict, help_text='Track which fields user manually edited')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_bill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_source', to='purchases.supplierbill')),
                ('matched_supplier', models.ForeignKey(blank=True, help_text='Auto-matched supplier from database', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_scans', to='suppliers.supplier')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_bill_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill Scan',
                'verbose_name_plural': 'Bill Scans',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['processing_status', 'uploaded_at'], name='purchases_b_process_142965_idx'), models.Index(fields=['uploaded_by', 'processing_status'], name='purchases_b_uploade_2341b0_idx')],
            },
        ),
    ]
