# Generated by Django 5.2.4 on 2026-01-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_billscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='billscan',
            name='summary',
            field=models.CharField(blank=True, help_text='AI-generated summary of bill line items/contents (max 256 chars)', max_length=256, null=True),
        ),
    ]
