# Generated by Django 5.2.5 on 2025-08-19 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(blank=True, help_text='Company ID for multi-tenant support', null=True)),
                ('entity_type', models.CharField(choices=[('quotation', 'Quotation'), ('job_ticket', 'Job Ticket'), ('customer', 'Customer'), ('order', 'Order'), ('invoice', 'Invoice')], max_length=50)),
                ('entity_id', models.BigIntegerField()),
                ('entity_ref', models.CharField(help_text="e.g. 'Quotation #241551' for quick list rendering", max_length=120)),
                ('due_at', models.DateTimeField(help_text='Timezone-aware datetime stored in UTC')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('snoozed', 'Snoozed'), ('done', 'Done'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('origin_module', models.CharField(blank=True, help_text='Module where reminder was created', max_length=50)),
                ('auto_cancel_on_states', models.JSONField(blank=True, default=list, help_text='States that auto-cancel this reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_path', models.TextField(blank=True, help_text='Relative URL for navigation')),
                ('assignee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reminders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reminders',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email_digest', 'Email Digest')], default='in_app', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reminders.reminder')),
            ],
            options={
                'db_table': 'reminders_notifications',
            },
        ),
        migrations.CreateModel(
            name='ReminderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('snooze', 'Snooze'), ('done', 'Done'), ('cancel', 'Cancel'), ('deliver', 'Deliver')], max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='reminders.reminder')),
            ],
            options={
                'db_table': 'reminders_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['assignee_user', 'status', 'due_at'], name='idx_reminders_assignee_due'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_reminders_entity'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['company_id', 'assignee_user'], name='idx_reminders_company'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'sent'])), fields=('entity_type', 'entity_id', 'assignee_user'), name='unique_active_reminder_per_entity_user'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='idx_notifications_user_unread'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['delivered_at'], name='idx_notifications_delivered'),
        ),
    ]
