# Generated by Django 5.2.5 on 2025-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft delete flag - hides notification from UI'),
        ),
    ]
