# Generated by Django 5.2.4 on 2026-01-04 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('debit_normal', 'Debit Normal'), ('credit_normal', 'Credit Normal')], help_text='Normal balance type for this category', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in reports (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account Category',
                'verbose_name_plural': 'Account Categories',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(db_index=True, help_text='Unique account code (e.g., 1000, 1010)', max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('is_system_account', models.BooleanField(default=False, help_text='System accounts cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_transactions', models.BooleanField(default=True, help_text='False for parent accounts that only group sub-accounts')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current account balance (updated by journal entries)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accountcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_accounts', to=settings.AUTH_USER_MODEL)),
                ('parent_account', models.ForeignKey(blank=True, help_text='Parent account for hierarchical structure', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_accounts', to='accounting.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['account_code'],
                'indexes': [models.Index(fields=['account_code'], name='accounting__account_2e7f20_idx'), models.Index(fields=['category', 'is_active'], name='accounting__categor_b6b6cd_idx')],
            },
        ),
    ]
