# Generated by Django 5.2.4 on 2026-01-04 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Period name (e.g., 'January 2026', 'Q1 2026')", max_length=100)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('locked', 'Locked')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_fiscal_periods', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fiscal_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiscal Period',
                'verbose_name_plural': 'Fiscal Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_number', models.CharField(db_index=True, help_text='Unique journal number (e.g., JE-20260104-0001)', max_length=50, unique=True)),
                ('entry_date', models.DateField(db_index=True, help_text='Date of the journal entry')),
                ('entry_type', models.CharField(choices=[('system', 'System Generated'), ('manual', 'Manual Entry')], default='system', max_length=20)),
                ('source_type', models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('invoice_payment', 'Invoice Payment'), ('pos_transaction', 'POS Transaction'), ('pos_zreport', 'POS Z Report'), ('supplier_bill', 'Supplier Bill'), ('bill_payment', 'Bill Payment'), ('payout_voucher', 'Payout Voucher'), ('manual', 'Manual Entry'), ('opening_balance', 'Opening Balance')], db_index=True, max_length=50)),
                ('source_id', models.IntegerField(blank=True, db_index=True, help_text='ID of source document', null=True)),
                ('source_reference', models.CharField(blank=True, help_text='Human-readable reference (e.g., invoice number)', max_length=255, null=True)),
                ('description', models.TextField(help_text='Description of the transaction')),
                ('is_posted', models.BooleanField(db_index=True, default=False, help_text='Posted entries are locked and immutable')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all debit lines', max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all credit lines', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.fiscalperiod')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-entry_date', '-journal_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Debit amount (use 0 for credit lines)', max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Credit amount (use 0 for debit lines)', max_digits=15)),
                ('description', models.CharField(blank=True, help_text='Line-specific description', max_length=500, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.chartofaccounts')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Line',
                'verbose_name_plural': 'Journal Lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='accounting__start_d_9f449b_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['status'], name='accounting__status_ee6e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['journal_number'], name='accounting__journal_ff8c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_date', 'is_posted'], name='accounting__entry_d_148219_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='accounting__source__3d844c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['is_posted'], name='accounting__is_post_95b69a_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('source_type', 'source_id'), name='unique_source_journal'),
        ),
    ]
