# Generated by Django 5.2.4 on 2026-01-04 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_fiscalperiod_journalentry_journalline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('invoice_payment', 'Invoice Payment'), ('pos_transaction', 'POS Transaction'), ('pos_zreport', 'POS Z Report'), ('supplier_bill', 'Supplier Bill'), ('bill_payment', 'Bill Payment'), ('payout_voucher', 'Payout Voucher'), ('bank_transaction', 'Bank Transaction'), ('manual', 'Manual Entry'), ('opening_balance', 'Opening Balance')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True, help_text='Date of the bank transaction')),
                ('transaction_type', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('transfer', 'Transfer'), ('bank_charge', 'Bank Charge'), ('interest', 'Interest'), ('other', 'Other')], db_index=True, max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference, cheque number, or transaction ID', max_length=100, null=True)),
                ('description', models.TextField(help_text='Transaction description')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted to Ledger')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_bank_transactions', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(help_text='Bank account (1010, 1020, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='accounting.chartofaccounts')),
                ('contra_account', models.ForeignKey(blank=True, help_text='Contra account for receipt/payment (e.g., AR, AP, Expense)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contra_bank_transactions', to='accounting.chartofaccounts')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bank_transactions', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transaction', to='accounting.journalentry')),
                ('transfer_to_account', models.ForeignKey(blank=True, help_text='Destination account for transfers', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transfers_received', to='accounting.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_date', 'status'], name='accounting__transac_03c4a6_idx'), models.Index(fields=['bank_account', 'transaction_date'], name='accounting__bank_ac_ef2ddd_idx'), models.Index(fields=['status'], name='accounting__status_f25954_idx')],
            },
        ),
    ]
