# Generated by Django 5.2.4 on 2026-01-04 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_journalentry_source_type_banktransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_reversed',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this entry has been reversed'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_at',
            field=models.DateTimeField(blank=True, help_text='When this entry was reversed', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_by',
            field=models.ForeignKey(blank=True, help_text='User who created the reversal entry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reverses',
            field=models.ForeignKey(blank=True, help_text='Original entry that this entry reverses (if this is a reversal)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entries', to='accounting.journalentry'),
        ),
    ]
