# Generated by Django 5.2.4 on 2026-01-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_journalentry_is_reversed_journalentry_reversed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('invoice_payment', 'Invoice Payment'), ('sales_credit_note', 'Sales Credit Note'), ('pos_transaction', 'POS Transaction'), ('pos_zreport', 'POS Z Report'), ('supplier_bill', 'Supplier Bill'), ('bill_payment', 'Bill Payment'), ('supplier_credit_note', 'Supplier Credit Note'), ('payout_voucher', 'Payout Voucher'), ('bank_transaction', 'Bank Transaction'), ('manual', 'Manual Entry'), ('opening_balance', 'Opening Balance')], db_index=True, max_length=50),
        ),
    ]
