# Generated by Codex on 2026-01-XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_journalentry_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='event_type',
            field=models.CharField(
                db_index=True,
                default='legacy',
                help_text='Specific event type for idempotency (e.g., invoice_sent, bill_payment_created)',
                max_length=100
            ),
            preserve_default=False,
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='accounting__source__3d844c_idx',
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id', 'event_type'], name='accounting__source__8c5b6d_idx'),
        ),
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='unique_source_journal',
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(
                condition=models.Q(('source_id__isnull', False)),
                fields=('source_type', 'source_id', 'event_type'),
                name='unique_source_event_journal',
            ),
        ),
    ]
