# Generated by Django 5.2.4 on 2026-01-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_add_event_type_and_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__source__2f1be4_idx',
            old_name='accounting__source__8c5b6d_idx',
        ),
    ]
