# Generated by Django 5.2.4 on 2026-02-06 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_account_mappings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='journalfailure',
            new_name='accounting__source__0f32eb_idx',
            old_name='accounting__source__c9f5ef_idx',
        ),
        migrations.RenameIndex(
            model_name='journalfailure',
            new_name='accounting__last_at_c35f7c_idx',
            old_name='accounting__last_at_6e4d50_idx',
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', True), ('source_reference__isnull', False)), fields=('source_type', 'event_type', 'source_reference'), name='unique_source_reference_event'),
        ),
    ]
