# Generated by Django 5.2.4 on 2025-07-21 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0006_costingestimating_remove_costingvariant_sheet_and_more'),
        ('customers', '0005_alter_customerdocument_file_alter_customer_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('quot_number', models.CharField(max_length=255, unique=True)),
                ('number_type', models.IntegerField(blank=True, choices=[(1, 'Quote'), (2, 'Estimate'), (3, 'Proposal')], null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_applied', models.BooleanField(default=True)),
                ('delivery_applied', models.BooleanField(default=True)),
                ('finalized', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('costing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='costing.costingestimating')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Sales Quotation',
                'verbose_name_plural': 'Sales Quotations',
                'db_table': 'sales_quotations',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_item_id', models.IntegerField(blank=True, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cs_profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cs_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cs_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='costing.costingsheet')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.salesquotation')),
            ],
            options={
                'verbose_name': 'Sales Quotation Item',
                'verbose_name_plural': 'Sales Quotation Items',
                'db_table': 'sales_quotation_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('printed', 'Printed'), ('emailed', 'Emailed'), ('sent', 'Sent to Customer'), ('accepted', 'Accepted by Customer'), ('rejected', 'Rejected by Customer'), ('expired', 'Expired'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='quotations.salesquotation')),
            ],
            options={
                'verbose_name': 'Sales Quotation Timeline',
                'verbose_name_plural': 'Sales Quotation Timeline',
                'db_table': 'sales_quotation_timeline',
                'ordering': ['-created_at'],
            },
        ),
    ]
