# Generated by Django 5.2.4 on 2025-07-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_alter_salesquotationtimeline_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesquotation',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='salesquotationitem',
            name='legacy_item_id',
        ),
    ]
