# Generated by Django 5.2.4 on 2025-07-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_remove_salesquotation_legacy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotation',
            name='private_notes',
            field=models.TextField(blank=True, help_text='Internal notes not visible to customer', null=True),
        ),
    ]
