# Generated by Django 5.2.4 on 2025-07-25 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_salesquotation_private_notes'),
        ('sales', '0003_finishedproductcategory_finishedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotationitem',
            name='finished_product',
            field=models.ForeignKey(blank=True, help_text='Reference to finished product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='sales.finishedproduct'),
        ),
    ]
