# Generated by Django 5.2.4 on 2025-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_salesquotationitem_finished_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotationitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
