# Generated by Django 5.2.4 on 2025-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_quotationshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotation',
            name='show_delivery_charges',
            field=models.BooleanField(default=True, help_text='Show delivery charges in quotation display'),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='show_subtotal',
            field=models.BooleanField(default=True, help_text='Show subtotal in quotation display'),
        ),
    ]
