# Generated by Django 5.2.4 on 2025-12-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_salesquotation_show_delivery_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotationtimeline',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('accepted', 'Accepted by Customer'), ('rejected', 'Rejected by Customer'), ('expired', 'Expired'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled'), ('converted', 'Converted to Order'), ('draft', 'Marked as Draft')], max_length=50),
        ),
    ]
