# Generated by Django 5.2.4 on 2026-01-18 00:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_alter_salesquotationtimeline_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotation',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='vat_rate',
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal('0.18'),
                help_text='VAT rate (e.g., 0.18 for 18%)',
                max_digits=5,
            ),
        ),
    ]
