# Generated by Django 5.2.4 on 2026-01-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_add_vat_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotation',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default=0.18, help_text='VAT rate (e.g., 0.18 for 18%)', max_digits=5),
        ),
    ]
