# Generated by Django 5.2.4 on 2025-07-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_a4_printer',
            field=models.CharField(blank=True, help_text='Default printer for A4 documents (quotations, invoices, orders, job tickets)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='default_a5_printer',
            field=models.CharField(blank=True, help_text='Default printer for A5 documents (dispatch notes, payment receipts)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='default_pos_printer',
            field=models.CharField(blank=True, help_text='Default thermal printer for POS receipts', max_length=255, null=True),
        ),
    ]
