# Generated by Django 5.2.4 on 2025-08-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_default_a4_printer_user_default_a5_printer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grid_rows_per_page',
            field=models.IntegerField(blank=True, help_text='Number of rows to display per page in grid views (1-100, null for auto)', null=True),
        ),
    ]
