# Generated by Django 5.2.4 on 2025-12-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_grid_rows_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('production', 'Production'), ('designer', 'Designer/Typesetter'), ('accounting', 'Accounting/Cashier')], default='production', max_length=50),
        ),
    ]
