# Generated by Django 5.2.4 on 2026-01-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sidebar_behavior',
            field=models.CharField(choices=[('overlay', 'Overlay'), ('push', 'Push Content')], default='overlay', max_length=10),
        ),
    ]
