# Generated by Django 5.2.4 on 2025-12-19 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('quotation', 'Quotation'), ('invoice', 'Invoice'), ('order', 'Order')], db_index=True, help_text='Type of document (Quotation, Invoice, or Order)', max_length=20)),
                ('doc_id', models.IntegerField(db_index=True, help_text='ID of the document in its respective table')),
                ('method', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('print', 'Print')], help_text='Communication method used', max_length=20)),
                ('destination', models.TextField(help_text='Email address, phone number, or "Physical Copy" for prints')),
                ('success', models.BooleanField(default=True, help_text='Whether the communication was successful')),
                ('message', models.TextField(blank=True, help_text='Additional details about the communication', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if communication failed', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the communication was sent')),
                ('sent_by', models.ForeignKey(help_text='User who initiated the communication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Communication Log',
                'verbose_name_plural': 'Document Communication Logs',
                'db_table': 'core_document_communication_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['doc_type', 'doc_id'], name='doc_type_id_idx'), models.Index(fields=['sent_at'], name='sent_at_idx')],
            },
        ),
    ]
