# Generated by Django 5.2.4 on 2026-01-04 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_pos_customer'),
        ('invoices', '0002_add_prepared_by_legacy_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(db_index=True, help_text='Credit note number (e.g., SCN-2026-001)', max_length=255, unique=True)),
                ('credit_note_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date of the credit note')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('applied', 'Applied'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Credit amount', max_digits=12)),
                ('reason', models.CharField(help_text='Reason for credit note (returns, adjustment, discount, etc.)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description', null=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When the credit note was applied', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_to_invoice', models.ForeignKey(blank=True, help_text='Invoice this credit note was applied to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_credit_notes', to='invoices.salesinvoice')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_sales_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer receiving the credit note', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, help_text='Original invoice being credited (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoices.salesinvoice')),
            ],
            options={
                'verbose_name': 'Sales Credit Note',
                'verbose_name_plural': 'Sales Credit Notes',
                'db_table': 'sales_credit_notes',
                'ordering': ['-credit_note_date', '-credit_note_number'],
            },
        ),
    ]
