# Generated by Django 5.2.4 on 2026-01-06 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_ar_payment_accounting'),
        ('customers', '0007_customer_pos_customer'),
        ('invoices', '0003_salescreditnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='cheque_clearance_journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry for cheque clearance (moves from 1040 to 1010)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheque_clearance_payments', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='cheque_cleared',
            field=models.BooleanField(default=False, help_text='Has cheque been cleared/deposited'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='cheque_cleared_date',
            field=models.DateField(blank=True, help_text='Date cheque was cleared', null=True),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Date on the cheque', null=True),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque number if payment method is cheque', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='deposit_account',
            field=models.ForeignKey(blank=True, help_text='Account to deposit payment to (1000=Cash, 1010=Bank, 1040=Cheques Received)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='is_void',
            field=models.BooleanField(default=False, help_text='Has this payment been voided'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry for this payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='void_reason',
            field=models.TextField(blank=True, help_text='Reason for voiding payment', null=True),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='voided_at',
            field=models.DateTimeField(blank=True, help_text='When payment was voided', null=True),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomerAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Original advance amount', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Remaining balance to apply', max_digits=12)),
                ('source_type', models.CharField(help_text="'overpayment' or 'prepayment'", max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('applied', 'Applied'), ('refunded', 'Refunded'), ('voided', 'Voided')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='customers.customer')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry that created this advance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_advances', to='accounting.journalentry')),
                ('source_payment', models.ForeignKey(blank=True, help_text='Payment that created this advance (for overpayments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advances', to='invoices.invoicepayment')),
            ],
            options={
                'verbose_name': 'Customer Advance',
                'verbose_name_plural': 'Customer Advances',
                'db_table': 'customer_advances',
                'ordering': ['-advance_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of payment allocated to this invoice', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='invoices.salesinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='invoices.invoicepayment')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
                'db_table': 'payment_allocations',
            },
        ),
    ]
