# Generated by Django 5.2.4 on 2026-01-06 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_ar_payment_accounting'),
        ('invoices', '0004_ar_payment_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='cheque_deposit_account',
            field=models.ForeignKey(blank=True, help_text='Bank account where cheque will be deposited/cleared to (e.g., 1010, 1020, 1030)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheque_deposits', to='accounting.chartofaccounts'),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='cheque_clearance_journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry for cheque clearance (moves from 1040 to selected bank account)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheque_clearance_payments', to='accounting.journalentry'),
        ),
    ]
