# Generated by Django 5.2.4 on 2026-01-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoicepayment_cheque_deposit_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='receipt_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the receipt was first generated', null=True),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, help_text='Receipt number for this payment (e.g., RCP-2026-00001)', max_length=50, null=True, unique=True),
        ),
    ]
