# Generated by Django 5.2.4 on 2026-01-17 10:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_receipt_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='advances_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total customer advances applied to this invoice', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='converted_to_tax_invoice_at',
            field=models.DateTimeField(blank=True, help_text='When proforma was converted to tax invoice', null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('proforma', 'Proforma Invoice'), ('tax_invoice', 'Tax Invoice')], db_index=True, default='proforma', help_text='Proforma invoices do not trigger VAT; Tax Invoices are legal VAT documents', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default=0.18, help_text='VAT rate (e.g., 0.18 for 18%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='is_vat_exempt',
            field=models.BooleanField(default=False, help_text='Item is VAT-exempt (Books, Newspapers, Educational materials)'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, help_text='Receipt number for this payment (e.g., R00001)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.18'), max_digits=5),
        ),
    ]
