# Generated by Django 5.1.3 on 2025-06-14 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_outbound', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('profit_margin', models.FloatField(default=0)),
                ('profit_amount', models.FloatField(default=0)),
                ('tax_percentage', models.FloatField(default=0)),
                ('tax_profit_amount', models.FloatField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='costing.costingsheet')),
            ],
        ),
        migrations.CreateModel(
            name='CostingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formula', models.TextField(blank=True, null=True)),
                ('calculated_cost', models.FloatField(default=0.0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='costing.costingvariant')),
            ],
        ),
    ]
