# Generated by Django 5.1.3 on 2025-06-17 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costingsheet',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
    ]
