# Generated by Django 5.1.3 on 2025-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_remove_costingsheet_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costingsheet',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costingsheet',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
