# Generated by Django 5.1.3 on 2025-06-21 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0003_costingsheet_updated_at_and_more'),
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costingsheet',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costing_sheets', to='employees.employee'),
        ),
    ]
