# Generated by Django 5.1.3 on 2025-07-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0004_costingsheet_sales_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='costingcomponent',
            table='costing_costingcomponent',
        ),
        migrations.AlterModelTable(
            name='costingsheet',
            table='costing_costingsheet',
        ),
        migrations.AlterModelTable(
            name='costingvariant',
            table='costing_costingvariant',
        ),
    ]
