# Generated by Django 5.1.3 on 2025-07-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0005_alter_costingcomponent_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostingEstimating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costingId', models.IntegerField()),
                ('customerId', models.IntegerField(blank=True, null=True)),
                ('customerName', models.CharField(blank=True, max_length=255, null=True)),
                ('projectName', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('isOutbound', models.SmallIntegerField(default=0)),
                ('isActive', models.IntegerField(default=1)),
                ('companyId', models.IntegerField(blank=True, null=True)),
                ('createdBy', models.IntegerField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('updatedBy', models.IntegerField(blank=True, null=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'costing_costing_estimating',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='costingvariant',
            name='sheet',
        ),
        migrations.AlterModelOptions(
            name='costingsheet',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='costingsheet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='costingsheet',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='costingsheet',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='costingsheet',
            name='is_outbound',
        ),
        migrations.RemoveField(
            model_name='costingsheet',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='costingsheet',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='costingsheet',
            name='sales_person',
        ),
        migrations.RemoveField(
            model_name='costingsheet',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='activeSheet',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='costingId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='formulas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='is_locked',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='profitAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='profitMargin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='subTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='taxPercentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='taxProfitAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='unitPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterModelTable(
            name='costingsheet',
            table='costing_costing_sheet',
        ),
        migrations.DeleteModel(
            name='CostingComponent',
        ),
        migrations.DeleteModel(
            name='CostingVariant',
        ),
    ]
