# Generated by Django 5.2.5 on 2025-12-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0006_costingestimating_remove_costingvariant_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costingsheet',
            name='finished_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costingsheet',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
