# Generated by Django 5.1.3 on 2025-06-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
