# Generated by Django 5.2.4 on 2025-08-08 13:13

import apps.employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Local profile picture file', null=True, upload_to=apps.employees.models.profile_picture_upload_path),
        ),
    ]
