# Generated by Django 5.2.4 on 2025-08-24 08:07

import apps.employees.models
import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_convert_profile_picture_to_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Local profile picture file', null=True, storage=config.storage.LocalProfilePictureStorage(), upload_to=apps.employees.models.profile_picture_upload_path),
        ),
    ]
