# Generated by Django 5.2.4 on 2025-12-31 04:59

import apps.sales.orders.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0007_costingsheet_finished_product_id_costingsheet_name'),
        ('customers', '0007_customer_pos_customer'),
        ('quotations', '0009_alter_salesquotationtimeline_event_type'),
        ('sales', '0005_change_quantity_to_integer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('number_type', models.IntegerField(choices=[(1, 'Order'), (2, 'Work Order'), (3, 'Job Order')], default=1)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('required_date', models.DateField(blank=True, help_text='Customer requested delivery date', null=True)),
                ('production_start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('production', 'In Production'), ('ready', 'Ready for Pickup/Delivery'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('po_so_number', models.CharField(blank=True, help_text='Customer PO/SO reference', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal production notes', null=True)),
                ('customer_notes', models.TextField(blank=True, help_text='Notes visible to customer', null=True)),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('legacy_order_id', models.CharField(blank=True, help_text='Legacy pressmanager_db order ID', max_length=255, null=True, unique=True)),
                ('prepared_from', models.CharField(blank=True, help_text='Source: quotation, costing, direct', max_length=50, null=True)),
                ('prepared_reff', models.CharField(blank=True, help_text='Reference to source document', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('costing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='costing.costingestimating')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer')),
                ('prepared_by', models.ForeignKey(blank=True, help_text='User who prepared this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_orders', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(blank=True, help_text='Source quotation if order was converted from quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_orders', to='quotations.salesquotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'db_table': 'sales_orders',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('view_count', models.IntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_shares', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='orders.salesorder')),
            ],
            options={
                'verbose_name': 'Order Share',
                'verbose_name_plural': 'Order Shares',
                'db_table': 'sales_order_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.sales.orders.models.order_attachment_upload_path)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(choices=[('artwork', 'Artwork'), ('specification', 'Specification'), ('customer_file', 'Customer File'), ('proof', 'Proof'), ('other', 'Other')], default='other', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.salesorder')),
            ],
            options={
                'verbose_name': 'Order Attachment',
                'verbose_name_plural': 'Order Attachments',
                'db_table': 'sales_order_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Product name snapshot', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Product description snapshot', null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='quantity * unit_price', max_digits=10)),
                ('cs_profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cs_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cs_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_ticket_generated', models.BooleanField(default=False, help_text='Has job ticket been generated')),
                ('job_ticket_number', models.CharField(blank=True, max_length=255, null=True)),
                ('production_notes', models.TextField(blank=True, help_text='Specific production notes for this item', null=True)),
                ('item_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('production', 'In Production'), ('completed', 'Completed')], default='pending', max_length=20, null=True)),
                ('costing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='costing.costingsheet')),
                ('finished_product', models.ForeignKey(blank=True, help_text='Reference to finished product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='sales.finishedproduct')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.salesorder')),
            ],
            options={
                'verbose_name': 'Sales Order Item',
                'verbose_name_plural': 'Sales Order Items',
                'db_table': 'sales_order_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Order Created'), ('confirmed', 'Order Confirmed'), ('production_started', 'Production Started'), ('production_completed', 'Production Completed'), ('ready', 'Ready for Pickup/Delivery'), ('delivered', 'Delivered to Customer'), ('invoiced', 'Invoiced'), ('completed', 'Order Completed'), ('cancelled', 'Order Cancelled'), ('modified', 'Order Modified'), ('converted', 'Converted from Quotation'), ('job_ticket_generated', 'Job Ticket Generated'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added')], max_length=50)),
                ('message', models.TextField()),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='orders.salesorder')),
            ],
            options={
                'verbose_name': 'Sales Order Timeline',
                'verbose_name_plural': 'Sales Order Timeline',
                'db_table': 'sales_order_timeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_number'], name='sales_order_order_n_51d36c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='sales_order_status_1f3c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_date'], name='sales_order_order_d_45d09c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer'], name='sales_order_custome_21b704_idx'),
        ),
    ]
