# Generated by Django 5.2.4 on 2026-01-17 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_ar_payment_accounting'),
        ('orders', '0003_add_production_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total advances paid against this order', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance (net_total - amount_paid)', max_digits=12),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cheque_number', models.CharField(blank=True, help_text='Cheque number if payment method is cheque', max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, help_text='Date on the cheque', null=True)),
                ('cheque_cleared', models.BooleanField(default=False, help_text='Has cheque been cleared/deposited')),
                ('cheque_cleared_date', models.DateField(blank=True, help_text='Date cheque was cleared', null=True)),
                ('is_void', models.BooleanField(default=False, help_text='Has this payment been voided')),
                ('void_reason', models.TextField(blank=True, help_text='Reason for voiding payment', null=True)),
                ('voided_at', models.DateTimeField(blank=True, help_text='When payment was voided', null=True)),
                ('receipt_number', models.CharField(blank=True, db_index=True, help_text='Receipt number for this payment (e.g., R00001)', max_length=50, null=True, unique=True)),
                ('receipt_generated_at', models.DateTimeField(blank=True, help_text='When the receipt was first generated', null=True)),
                ('cheque_clearance_journal_entry', models.ForeignKey(blank=True, help_text='Journal entry for cheque clearance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_cheque_clearance_payments', to='accounting.journalentry')),
                ('cheque_deposit_account', models.ForeignKey(blank=True, help_text='Bank account where cheque will be deposited', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_cheque_deposits', to='accounting.chartofaccounts')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deposit_account', models.ForeignKey(blank=True, help_text='Account to deposit payment to (1000=Cash, 1010=Bank, 1040=Cheques Received)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_payments', to='accounting.chartofaccounts')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry for this advance payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_payments', to='accounting.journalentry')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.salesorder')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_order_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
                'db_table': 'sales_order_payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
