# Generated by Django 5.1.3 on 2025-07-05 08:49

import apps.customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocument',
            name='file',
            field=models.FileField(upload_to=apps.customers.models.customer_document_upload_path),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers_customer',
        ),
        migrations.AlterModelTable(
            name='customeraddress',
            table='customers_customeraddress',
        ),
        migrations.AlterModelTable(
            name='customeraltcontact',
            table='customers_customeraltcontact',
        ),
        migrations.AlterModelTable(
            name='customerdocument',
            table='customers_customerdocument',
        ),
    ]
