# Generated by Django 5.2.4 on 2025-12-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customeremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pos_customer',
            field=models.BooleanField(default=False, help_text='Mark as POS walk-in customer'),
        ),
    ]
