# Generated by Django 5.2.4 on 2025-12-24 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_customer_pos_customer'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDrawerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.CharField(help_text="Unique session identifier (e.g., 'CD-20250124-001')", max_length=50, unique=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, help_text='Starting cash in drawer', max_digits=10)),
                ('opening_notes', models.TextField(blank=True, help_text='Notes at opening (e.g., denomination breakdown)', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When drawer was closed', null=True)),
                ('expected_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Expected cash (opening + sales - account payments)', max_digits=10, null=True)),
                ('actual_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Actual counted cash at closing', max_digits=10, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, help_text='Difference (actual - expected)', max_digits=10, null=True)),
                ('closing_notes', models.TextField(blank=True, help_text='Notes at closing (denomination breakdown, variance explanation)', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('reconciled', 'Reconciled')], default='open', max_length=20)),
                ('reconciled_at', models.DateTimeField(blank=True, help_text='When variance was reviewed/approved', null=True)),
                ('location', models.ForeignKey(help_text='Physical location of cash drawer', on_delete=django.db.models.deletion.PROTECT, related_name='cash_drawer_sessions', to='inventory.inventorylocation')),
                ('reconciled_by', models.ForeignKey(blank=True, help_text='Manager who approved variance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User operating this drawer', on_delete=django.db.models.deletion.PROTECT, related_name='cash_drawer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Drawer Session',
                'verbose_name_plural': 'Cash Drawer Sessions',
                'db_table': 'pos_cash_drawer_sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current outstanding balance (negative = credit, positive = owes)', max_digits=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum credit allowed', max_digits=10)),
                ('payment_term_days', models.IntegerField(default=30, help_text='Payment due days (e.g., Net 30)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether account is active for new charges')),
                ('is_suspended', models.BooleanField(default=False, help_text='Account suspended due to overdue balance')),
                ('last_transaction_date', models.DateTimeField(blank=True, help_text='Last charge or payment date', null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, help_text='Last payment received date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_accounts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(help_text='Customer with account privileges', on_delete=django.db.models.deletion.PROTECT, related_name='account', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Account',
                'verbose_name_plural': 'Customer Accounts',
                'db_table': 'pos_customer_accounts',
                'ordering': ['customer__name'],
            },
        ),
        migrations.CreateModel(
            name='POSQuickServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text="Button label (e.g., 'B/W Photocopy')", max_length=100)),
                ('display_order', models.IntegerField(default=0, help_text='Order for UI display (lower = higher priority)')),
                ('button_color', models.CharField(default='#3B82F6', help_text='Hex color code for button (e.g., #3B82F6 for blue)', max_length=7)),
                ('icon_name', models.CharField(blank=True, help_text="Icon identifier (e.g., 'printer', 'copy')", max_length=50, null=True)),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, help_text='Custom price (if null, uses stock item default)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to show in POS interface')),
                ('default_quantity', models.IntegerField(default=1, help_text='Default quantity when clicked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quick_items', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(help_text='Linked inventory item', on_delete=django.db.models.deletion.PROTECT, related_name='quick_service_items', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'POS Quick Service Item',
                'verbose_name_plural': 'POS Quick Service Items',
                'db_table': 'pos_quick_service_items',
                'ordering': ['display_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text="Unique receipt number (e.g., 'RCP-20250124-0001')", max_length=50, unique=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='When transaction was created')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all line items before tax', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount applied', max_digits=10)),
                ('discount_reason', models.CharField(blank=True, help_text='Reason for discount', max_length=255, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total tax', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Final total (subtotal - discount + tax)', max_digits=10)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided'), ('refunded', 'Refunded'), ('partial_refund', 'Partial Refund')], default='completed', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, help_text='When transaction was voided', null=True)),
                ('void_reason', models.TextField(blank=True, help_text='Reason for voiding', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional transaction notes', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_drawer_session', models.ForeignKey(help_text='Cash drawer session this transaction belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='pos.cashdrawersession')),
                ('created_by', models.ForeignKey(help_text='User who processed transaction', on_delete=django.db.models.deletion.PROTECT, related_name='created_pos_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer (null for anonymous walk-in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_transactions', to='customers.customer')),
                ('location', models.ForeignKey(help_text='Location where sale occurred', on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to='inventory.inventorylocation')),
                ('voided_by', models.ForeignKey(blank=True, help_text='User who voided transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Transaction',
                'verbose_name_plural': 'POS Transactions',
                'db_table': 'pos_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='POSPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('account', 'Customer Account'), ('bank_transfer', 'Bank Transfer'), ('mobile_payment', 'Mobile Payment'), ('other', 'Other')], help_text='Payment method used', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid via this method', max_digits=10)),
                ('reference_number', models.CharField(blank=True, help_text='Card transaction ID, check number, transfer reference, etc.', max_length=100, null=True)),
                ('customer_account_balance_before', models.DecimalField(blank=True, decimal_places=2, help_text='Customer account balance before this payment (for account payments)', max_digits=10, null=True)),
                ('customer_account_balance_after', models.DecimalField(blank=True, decimal_places=2, help_text='Customer account balance after this payment (for account payments)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Payment notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pos_payments', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(help_text='Parent transaction', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.postransaction')),
            ],
            options={
                'verbose_name': 'POS Payment',
                'verbose_name_plural': 'POS Payments',
                'db_table': 'pos_payments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge (Sale)'), ('payment', 'Payment'), ('adjustment', 'Balance Adjustment'), ('refund', 'Refund')], help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (positive = charge, negative = payment)', max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Account balance before this transaction', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Account balance after this transaction', max_digits=10)),
                ('reference_number', models.CharField(blank=True, help_text='Payment reference or invoice number', max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Payment due date (for charges)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Transaction notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Customer account', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pos.customeraccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_transactions', to=settings.AUTH_USER_MODEL)),
                ('pos_transaction', models.ForeignKey(blank=True, help_text='Related POS transaction (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='pos.postransaction')),
            ],
            options={
                'verbose_name': 'Customer Account Transaction',
                'verbose_name_plural': 'Customer Account Transactions',
                'db_table': 'pos_customer_account_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Product name at time of sale', max_length=255)),
                ('sku', models.CharField(help_text='SKU at time of sale', max_length=100)),
                ('quantity', models.IntegerField(help_text='Quantity sold')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit (before tax)', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate percentage applied', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total tax for this line (calculated)', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount applied to this line', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total for line (quantity * unit_price - discount + tax)', max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit at time of sale (for COGS)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Line item notes (e.g., customization details)', null=True)),
                ('stock_item', models.ForeignKey(help_text='Product sold', on_delete=django.db.models.deletion.PROTECT, related_name='pos_transaction_items', to='inventory.stockitem')),
                ('transaction', models.ForeignKey(help_text='Parent transaction', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.postransaction')),
            ],
            options={
                'verbose_name': 'POS Transaction Item',
                'verbose_name_plural': 'POS Transaction Items',
                'db_table': 'pos_transaction_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='cashdrawersession',
            index=models.Index(fields=['user', 'status', 'opened_at'], name='idx_session_user_status'),
        ),
        migrations.AddIndex(
            model_name='cashdrawersession',
            index=models.Index(fields=['location', 'opened_at'], name='idx_session_loc_date'),
        ),
        migrations.AddIndex(
            model_name='cashdrawersession',
            index=models.Index(fields=['status'], name='idx_session_status'),
        ),
        migrations.AddConstraint(
            model_name='cashdrawersession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('user', 'location'), name='unique_open_session_per_user_location'),
        ),
        migrations.AddIndex(
            model_name='customeraccount',
            index=models.Index(fields=['is_active', 'current_balance'], name='idx_account_active_balance'),
        ),
        migrations.AddIndex(
            model_name='customeraccount',
            index=models.Index(fields=['is_suspended'], name='idx_account_suspended'),
        ),
        migrations.AddIndex(
            model_name='posquickserviceitem',
            index=models.Index(fields=['is_active', 'display_order'], name='idx_quick_item_active_order'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['receipt_number'], name='idx_pos_receipt_number'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['transaction_date'], name='idx_pos_transaction_date'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['customer', 'transaction_date'], name='idx_pos_customer_date'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['cash_drawer_session'], name='idx_pos_session'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['status'], name='idx_pos_status'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['location', 'transaction_date'], name='idx_pos_loc_date'),
        ),
        migrations.AddIndex(
            model_name='pospayment',
            index=models.Index(fields=['transaction'], name='idx_payment_transaction'),
        ),
        migrations.AddIndex(
            model_name='pospayment',
            index=models.Index(fields=['payment_method', 'created_at'], name='idx_payment_method_date'),
        ),
        migrations.AddIndex(
            model_name='customeraccounttransaction',
            index=models.Index(fields=['account', 'created_at'], name='idx_acct_txn_account_date'),
        ),
        migrations.AddIndex(
            model_name='customeraccounttransaction',
            index=models.Index(fields=['transaction_type'], name='idx_acct_txn_type'),
        ),
        migrations.AddIndex(
            model_name='customeraccounttransaction',
            index=models.Index(fields=['due_date'], name='idx_acct_txn_due_date'),
        ),
        migrations.AddIndex(
            model_name='postransactionitem',
            index=models.Index(fields=['transaction'], name='idx_pos_item_transaction'),
        ),
        migrations.AddIndex(
            model_name='postransactionitem',
            index=models.Index(fields=['stock_item'], name='idx_pos_item_stock'),
        ),
    ]
