# Generated by Django 5.2.4 on 2025-12-24 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_pos_customer'),
        ('inventory', '0002_stockitem_sales_count'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text="Unique 6-digit order number (e.g., '123456')", max_length=6, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('voided', 'Voided')], default='pending_payment', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all line items before tax', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount applied', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total tax', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Final total (subtotal - discount + tax)', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Order notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was accepted', null=True)),
                ('voided_at', models.DateTimeField(blank=True, help_text='When order was voided', null=True)),
                ('void_reason', models.TextField(blank=True, help_text='Reason for voiding', null=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text='Accounting/Cashier who accepted payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_pos_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Designer/Typesetter who created the order', on_delete=django.db.models.deletion.PROTECT, related_name='created_pos_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer (null for anonymous walk-in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to='customers.customer')),
                ('location', models.ForeignKey(help_text='Location where order was created', on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to='inventory.inventorylocation')),
                ('related_transaction', models.ForeignKey(blank=True, help_text='Final POS transaction created after payment acceptance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_order', to='pos.postransaction')),
                ('voided_by', models.ForeignKey(blank=True, help_text='User who voided the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_pos_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Order',
                'verbose_name_plural': 'POS Orders',
                'db_table': 'pos_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Product name at time of order', max_length=255)),
                ('sku', models.CharField(help_text='SKU at time of order', max_length=100)),
                ('quantity', models.IntegerField(help_text='Quantity ordered')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit (before tax)', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate percentage applied', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total tax for this line (calculated)', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount applied to this line', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total for line (quantity * unit_price - discount + tax)', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Line item notes', null=True)),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.posorder')),
                ('stock_item', models.ForeignKey(help_text='Product ordered', on_delete=django.db.models.deletion.PROTECT, related_name='pos_order_items', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'POS Order Item',
                'verbose_name_plural': 'POS Order Items',
                'db_table': 'pos_order_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['order_number'], name='idx_order_number'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['created_by', 'created_at'], name='idx_order_creator_date'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['created_at'], name='idx_order_created_at'),
        ),
        migrations.AddIndex(
            model_name='posorderitem',
            index=models.Index(fields=['order'], name='idx_order_item_order'),
        ),
        migrations.AddIndex(
            model_name='posorderitem',
            index=models.Index(fields=['stock_item'], name='idx_order_item_stock'),
        ),
    ]
