# Generated by Django 5.2.4 on 2025-12-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_posorder_posorderitem_posorder_idx_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='order_number',
            field=models.CharField(help_text="Unique daily sequential order number (e.g., '251225001')", max_length=12, unique=True),
        ),
    ]
