# Generated by Django 5.2.4 on 2025-12-26 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_posorder_order_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POSQuickServiceItem',
        ),
    ]
