# Generated by Django 5.2.4 on 2025-12-26 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_delete_posquickserviceitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether category is active')),
                ('display_order', models.IntegerField(default=0, help_text='Display order for sorting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'POS Category',
                'verbose_name_plural': 'POS Categories',
                'db_table': 'pos_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='POSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location name', max_length=100)),
                ('code', models.CharField(help_text="Location code (e.g., 'MAIN')", max_length=20, unique=True)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('is_active', models.BooleanField(default=True, help_text='Whether location is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'POS Location',
                'verbose_name_plural': 'POS Locations',
                'db_table': 'pos_locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cashdrawersession',
            name='pos_location',
            field=models.ForeignKey(blank=True, help_text='POS Location (new system)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_drawer_sessions', to='pos.poslocation'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='pos_location',
            field=models.ForeignKey(blank=True, help_text='POS Location (new system)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pos.poslocation'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='pos_location',
            field=models.ForeignKey(blank=True, help_text='POS Location (new system)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='pos.poslocation'),
        ),
        migrations.CreateModel(
            name='POSProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('sku', models.CharField(blank=True, help_text='Stock keeping unit code', max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('default_selling_price', models.DecimalField(decimal_places=2, help_text='Default selling price', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Unit cost (for profit calculations)', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default tax rate percentage', max_digits=5)),
                ('is_quick_access', models.BooleanField(default=False, help_text='Show in quick access panel')),
                ('display_order', models.IntegerField(default=0, help_text='Display order in quick access')),
                ('button_color', models.CharField(default='#3B82F6', help_text='Quick access button color (hex)', max_length=7)),
                ('icon_name', models.CharField(blank=True, help_text='Icon name for quick access button', max_length=50)),
                ('default_quantity', models.IntegerField(default=1, help_text='Default quantity when added from quick access')),
                ('track_inventory', models.BooleanField(default=False, help_text='Track inventory for this product')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, help_text='Current quantity on hand', max_digits=10)),
                ('allow_backorder', models.BooleanField(default=True, help_text='Allow sales when out of stock')),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Low stock alert threshold', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Product is active and available for sale')),
                ('sales_count', models.IntegerField(default=0, help_text='Total number of sales (for popularity tracking)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.poscategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Product',
                'verbose_name_plural': 'POS Products',
                'db_table': 'pos_products',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='POS Product (new system)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='pos.posproduct'),
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='POS Product (new system)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='pos.posproduct'),
        ),
        migrations.CreateModel(
            name='POSStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('adjustment', 'Adjustment'), ('void', 'Void/Refund')], help_text='Type of movement', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity moved (negative for sales)', max_digits=10)),
                ('reference_type', models.CharField(help_text="Reference type (e.g., 'pos_transaction', 'adjustment')", max_length=50)),
                ('reference_id', models.IntegerField(help_text='ID of reference object')),
                ('notes', models.TextField(blank=True, help_text='Movement notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this movement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Location where movement occurred', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='pos.poslocation')),
                ('product', models.ForeignKey(help_text='Product being moved', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='pos.posproduct')),
            ],
            options={
                'verbose_name': 'POS Stock Movement',
                'verbose_name_plural': 'POS Stock Movements',
                'db_table': 'pos_stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='posproduct',
            index=models.Index(fields=['sku'], name='idx_pos_product_sku'),
        ),
        migrations.AddIndex(
            model_name='posproduct',
            index=models.Index(fields=['is_active', 'is_quick_access'], name='idx_pos_product_active_quick'),
        ),
        migrations.AddIndex(
            model_name='posproduct',
            index=models.Index(fields=['category'], name='idx_pos_product_category'),
        ),
        migrations.AddIndex(
            model_name='posstockmovement',
            index=models.Index(fields=['product', 'created_at'], name='idx_pos_movement_product'),
        ),
        migrations.AddIndex(
            model_name='posstockmovement',
            index=models.Index(fields=['location', 'created_at'], name='idx_pos_movement_location'),
        ),
        migrations.AddIndex(
            model_name='posstockmovement',
            index=models.Index(fields=['movement_type'], name='idx_pos_movement_type'),
        ),
    ]
