# Generated by Django 5.2.4 on 2025-12-26 04:36

from django.db import migrations


def setup_pos_data(apps, schema_editor):
    """
    Migrate data from inventory module to POS module.
    Creates POS location, categories, products and updates references.
    """
    POSLocation = apps.get_model('pos', 'POSLocation')
    POSCategory = apps.get_model('pos', 'POSCategory')
    POSProduct = apps.get_model('pos', 'POSProduct')
    POSOrderItem = apps.get_model('pos', 'POSOrderItem')
    POSTransactionItem = apps.get_model('pos', 'POSTransactionItem')
    POSOrder = apps.get_model('pos', 'POSOrder')
    POSTransaction = apps.get_model('pos', 'POSTransaction')
    CashDrawerSession = apps.get_model('pos', 'CashDrawerSession')

    try:
        StockItem = apps.get_model('inventory', 'StockItem')
        InventoryLocation = apps.get_model('inventory', 'InventoryLocation')
    except LookupError:
        # If inventory models don't exist, skip migration
        print("Inventory models not found, skipping POS data migration")
        return

    # 1. Create default POS location (from first inventory location or create new)
    inventory_location = InventoryLocation.objects.first()
    default_location = POSLocation.objects.create(
        name=inventory_location.name if inventory_location else 'Main Shop',
        code='MAIN',
        address=getattr(inventory_location, 'address', '') if inventory_location else '',
        is_active=True
    )
    print(f"Created POS Location: {default_location.name}")

    # 2. Create categories from FinishedProduct categories
    category_map = {}
    stock_item_to_product = {}  # Map old stock_item.id → new POSProduct

    # First pass: collect unique categories
    for stock_item in StockItem.objects.select_related('finished_product__category'):
        if stock_item.finished_product and stock_item.finished_product.category:
            cat = stock_item.finished_product.category
            if cat.id not in category_map:
                pos_cat, created = POSCategory.objects.get_or_create(
                    name=cat.category_name,
                    defaults={
                        'description': '',
                        'is_active': True
                    }
                )
                category_map[cat.id] = pos_cat
                if created:
                    print(f"Created POS Category: {pos_cat.name}")

    # 3. Create POS products from stock items
    products_created = 0
    for stock_item in StockItem.objects.select_related('finished_product__category'):
        category = None
        if stock_item.finished_product and stock_item.finished_product.category:
            category = category_map.get(stock_item.finished_product.category.id)

        pos_product = POSProduct.objects.create(
            name=stock_item.finished_product.name if stock_item.finished_product else f"Product {stock_item.id}",
            sku=stock_item.sku,
            category=category,
            default_selling_price=stock_item.default_selling_price,
            unit_cost=stock_item.unit_cost,
            tax_rate=stock_item.tax_rate,
            is_quick_access=stock_item.is_quick_access,
            display_order=stock_item.display_order if stock_item.display_order is not None else 0,
            button_color=stock_item.button_color or '#3B82F6',
            icon_name=stock_item.icon_name or '',
            default_quantity=stock_item.default_quantity if stock_item.default_quantity is not None else 1,
            track_inventory=False,  # Start with no tracking
            quantity_on_hand=0,
            allow_backorder=True,
            is_active=stock_item.is_active,
            sales_count=stock_item.sales_count if stock_item.sales_count is not None else 0
        )
        stock_item_to_product[stock_item.id] = pos_product
        products_created += 1

    print(f"Created {products_created} POS Products")

    # 4. Update POSOrderItem and POSTransactionItem product references
    order_items_updated = 0
    for order_item in POSOrderItem.objects.select_related('stock_item'):
        if order_item.stock_item_id and order_item.stock_item_id in stock_item_to_product:
            order_item.product = stock_item_to_product[order_item.stock_item_id]
            order_item.save(update_fields=['product'])
            order_items_updated += 1

    print(f"Updated {order_items_updated} POS Order Items")

    trans_items_updated = 0
    for trans_item in POSTransactionItem.objects.select_related('stock_item'):
        if trans_item.stock_item_id and trans_item.stock_item_id in stock_item_to_product:
            trans_item.product = stock_item_to_product[trans_item.stock_item_id]
            trans_item.save(update_fields=['product'])
            trans_items_updated += 1

    print(f"Updated {trans_items_updated} POS Transaction Items")

    # 5. Update location references in orders, transactions, sessions
    orders_updated = 0
    for order in POSOrder.objects.all():
        order.pos_location = default_location
        order.save(update_fields=['pos_location'])
        orders_updated += 1

    print(f"Updated {orders_updated} POS Orders")

    transactions_updated = 0
    for transaction in POSTransaction.objects.all():
        transaction.pos_location = default_location
        transaction.save(update_fields=['pos_location'])
        transactions_updated += 1

    print(f"Updated {transactions_updated} POS Transactions")

    sessions_updated = 0
    for session in CashDrawerSession.objects.all():
        session.pos_location = default_location
        session.save(update_fields=['pos_location'])
        sessions_updated += 1

    print(f"Updated {sessions_updated} Cash Drawer Sessions")
    print("POS data migration completed successfully!")


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_poscategory_poslocation_and_more'),
        ('inventory', '0001_initial'),  # Ensure inventory models exist
    ]

    operations = [
        migrations.RunPython(setup_pos_data, reverse_code=migrations.RunPython.noop),
    ]
