# Generated by Django 5.2.4 on 2025-12-26 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_setup_pos_data'),
    ]

    operations = [
        # Step 0: Remove old indexes/constraints that reference soon-to-be removed fields.
        migrations.RemoveIndex(
            model_name='posorderitem',
            name='idx_order_item_stock',
        ),
        migrations.RemoveIndex(
            model_name='postransactionitem',
            name='idx_pos_item_stock',
        ),
        migrations.RemoveIndex(
            model_name='cashdrawersession',
            name='idx_session_loc_date',
        ),
        migrations.RemoveIndex(
            model_name='postransaction',
            name='idx_pos_loc_date',
        ),
        migrations.RemoveConstraint(
            model_name='cashdrawersession',
            name='unique_open_session_per_user_location',
        ),

        # Step 1: Make product required in order and transaction items.
        migrations.AlterField(
            model_name='posorderitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='order_items',
                to='pos.posproduct',
                help_text='POS Product'
            ),
        ),
        migrations.AlterField(
            model_name='postransactionitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transaction_items',
                to='pos.posproduct',
                help_text='POS Product'
            ),
        ),

        # Step 2: Remove old stock_item fields.
        migrations.RemoveField(
            model_name='posorderitem',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='postransactionitem',
            name='stock_item',
        ),

        # Step 3: Remove old inventory location fields.
        migrations.RemoveField(
            model_name='posorder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='postransaction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='cashdrawersession',
            name='location',
        ),

        # Step 4: Rename pos_location to location and make required.
        migrations.RenameField(
            model_name='posorder',
            old_name='pos_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='postransaction',
            old_name='pos_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='cashdrawersession',
            old_name='pos_location',
            new_name='location',
        ),

        migrations.AlterField(
            model_name='posorder',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='orders',
                to='pos.poslocation',
                help_text='POS Location'
            ),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transactions',
                to='pos.poslocation',
                help_text='POS Location'
            ),
        ),
        migrations.AlterField(
            model_name='cashdrawersession',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='cash_drawer_sessions',
                to='pos.poslocation',
                help_text='POS Location'
            ),
        ),

        # Step 5: Re-add location-based indexes/constraints on the new location field.
        migrations.AddIndex(
            model_name='cashdrawersession',
            index=models.Index(fields=['location', 'opened_at'], name='idx_session_loc_date'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['location', 'transaction_date'], name='idx_pos_loc_date'),
        ),
        migrations.AddConstraint(
            model_name='cashdrawersession',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'open')),
                fields=('user', 'location'),
                name='unique_open_session_per_user_location',
            ),
        ),

        # Step 6: Add new indexes for product fields.
        migrations.AddIndex(
            model_name='posorderitem',
            index=models.Index(fields=['product'], name='idx_order_item_product'),
        ),
        migrations.AddIndex(
            model_name='postransactionitem',
            index=models.Index(fields=['product'], name='idx_pos_item_product'),
        ),
    ]
