# Generated by Django 5.2.4 on 2025-12-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_remove_inventory_dependencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posproduct',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='posproduct',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='posproduct',
            name='icon_name',
        ),
    ]
