# Generated by Django 5.2.4 on 2025-12-28 16:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_create_misc_custom_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdrawersession',
            name='commercial_printing_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Income from commercial printing (calculated manually from receipts)', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashdrawersession',
            name='payouts',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash paid out (hand-written vouchers)', max_digits=12),
        ),
    ]
