# Generated by Django 5.2.5 on 2025-08-22 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintCloudClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Computer/client name', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='online', max_length=20)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_printer_name', models.CharField(help_text="User's preferred printer name", max_length=255)),
                ('fallback_printer_names', models.JSONField(default=list, help_text='Alternative printer names if preferred unavailable')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('quotation', 'Quotation'), ('receipt', 'Receipt'), ('job_ticket', 'Job Ticket'), ('dispatch_note', 'Dispatch Note')], max_length=20)),
                ('print_data', models.TextField(help_text='Base64 encoded PDF content or ESC/POS commands')),
                ('copies', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('printing', 'Printing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('used_printer_name', models.CharField(blank=True, help_text='Actually used printer name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='printcloudclient.printcloudclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('driver', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_type', models.CharField(choices=[('standard', 'Standard Printer'), ('pos', 'POS/Thermal Printer')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('busy', 'Busy')], default='online', max_length=20)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('last_status_update', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='printcloudclient.printcloudclient')),
            ],
            options={
                'ordering': ['printer_type', 'name'],
                'unique_together': {('client', 'name')},
            },
        ),
    ]
