# Generated by Django 5.2.4 on 2025-08-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printcloudclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='print_data',
            field=models.TextField(help_text='Base64 encoded printer data (PDF, PCL, PostScript, or ESC/POS commands)'),
        ),
    ]
