# Generated by Django 5.2.4 on 2025-07-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Item name e.g., Books A4 (297mm x 210mm)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Default description template e.g., 128 Inside Pages 28 Colour Pages, 100 B/W Pages Printed on 70gsm Bank Paper', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sales Item',
                'verbose_name_plural': 'Sales Items',
                'db_table': 'sales_items',
                'ordering': ['item_name'],
            },
        ),
    ]
