# Generated by Django 5.2.4 on 2025-07-25 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_description_from_salesitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Category name e.g., Books, Stationery', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('income_account_id', models.CharField(help_text='Income account ID for accounting integration e.g., 4300', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='sales.finishedproductcategory')),
            ],
            options={
                'verbose_name': 'Finished Product Category',
                'verbose_name_plural': 'Finished Product Categories',
                'db_table': 'finished_product_categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name e.g., Books A4, Business Cards', max_length=255)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in mm', max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in mm', max_digits=8, null=True)),
                ('description', models.TextField(blank=True, help_text='Product description - leave blank for items with variable specifications')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.finishedproductcategory')),
            ],
            options={
                'verbose_name': 'Finished Product',
                'verbose_name_plural': 'Finished Products',
                'db_table': 'finished_products',
                'ordering': ['name'],
            },
        ),
    ]
