# Generated by Django 5.2.4 on 2025-07-25 13:48

from django.db import migrations


def populate_sample_data(apps, schema_editor):
    """Populate sample categories and products"""
    FinishedProductCategory = apps.get_model('sales', 'FinishedProductCategory')
    FinishedProduct = apps.get_model('sales', 'FinishedProduct')
    
    # Create categories
    books = FinishedProductCategory.objects.create(
        category_name='Books',
        description='All types of books',
        parent_category=None,
        income_account_id='4300',
        is_active=True
    )
    
    softcover_books = FinishedProductCategory.objects.create(
        category_name='Softcover Books',
        description='All softcover books',
        parent_category=books,
        income_account_id='4300',
        is_active=True
    )
    
    hardcover_books = FinishedProductCategory.objects.create(
        category_name='Hardcover Books',
        description='All hardcover books',
        parent_category=books,
        income_account_id='4300',
        is_active=True
    )
    
    stationery = FinishedProductCategory.objects.create(
        category_name='Stationery',
        description='Business cards, letterheads',
        parent_category=None,
        income_account_id='4400',
        is_active=True
    )
    
    large_format = FinishedProductCategory.objects.create(
        category_name='Large Format',
        description='Banners, posters, signage',
        parent_category=None,
        income_account_id='4200',
        is_active=True
    )
    
    photocopy = FinishedProductCategory.objects.create(
        category_name='Photocopy Services',
        description='Walk-in copying',
        parent_category=None,
        income_account_id='4100',
        is_active=True
    )
    
    # Create products
    FinishedProduct.objects.create(
        name='Books A4',
        width=297,
        height=210,
        description='',
        category=books,
        is_active=True
    )
    
    FinishedProduct.objects.create(
        name='Books A5',
        width=210,
        height=148,
        description='',
        category=books,
        is_active=True
    )
    
    FinishedProduct.objects.create(
        name='Business Cards',
        width=90,
        height=50,
        description='Standard business cards on 350gsm art card',
        category=stationery,
        is_active=True
    )
    
    FinishedProduct.objects.create(
        name='Letterheads A4',
        width=297,
        height=210,
        description='',
        category=stationery,
        is_active=True
    )


def reverse_sample_data(apps, schema_editor):
    """Remove sample data"""
    FinishedProductCategory = apps.get_model('sales', 'FinishedProductCategory')
    FinishedProduct = apps.get_model('sales', 'FinishedProduct')
    
    FinishedProduct.objects.all().delete()
    FinishedProductCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_finishedproductcategory_finishedproduct'),
    ]

    operations = [
        migrations.RunPython(populate_sample_data, reverse_sample_data),
    ]
