# Generated by Django 5.2.4 on 2025-07-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20250725_0848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesItem',
        ),
    ]
