# Generated by Django 5.2.4 on 2026-01-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_change_quantity_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='is_vat_exempt',
            field=models.BooleanField(default=False, help_text='Check for VAT-exempt items (Books, Newspapers, Educational materials)'),
        ),
    ]
